version: "3.8"

services:
  bot:
    build: .
    container_name: telegram_bot
    depends_on:
      - mongodb
    env_file:
      - bot/config/.env
    command: python -m bot.main
    volumes:
      - .:/app
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: unless-stopped
